### PR TITLE
fix to install script/launch

### PR DESCRIPTION
**Pull request by k-okada**

### CODE REVIEW

**Comment by trainman419** [comment]
If you're removing the catkin_python_setup, you should remove that line from the makefile completely, and remove the setup.py as well, since it's now unused.

**Comment by k-okada** [comment]
ok, done

**Comment by trainman419** [comment]
Looks good!

Care to review @ibaranov-cp or @TheDash ?

**Comment by ibaranov-cp** [comment]
We will do asap.

**Comment by UltronDestroyer** [comment]
I'm seeing that before, there were no launch files generated for the system. This fix makes them available. @ibaranov-cp

**Pull request merged**
