### PR TITLE
catkinize rest of the packages

### PR DESCRIPTION
**Pull request by k-okada**
to move https://github.com/PR2/pr2_navigation/pull/3#issuecomment-44424633 forward

### CODE REVIEW

**Comment by UltronDestroyer** [comment]
Hello again,

I have sourced your code and here is the output. I assume I'm missing some package/message generation for GetKinematicsSolver. What package is required for this, I'm having trouble finding it?

[ 66%] Building CXX object pr2_apps/pr2_teleop_general/CMakeFiles/pr2_teleop_general_commander.dir/src/pr2_teleop_general_commander.cpp.o
/home/marco/overlay_ws/src/pr2_apps/pr2_teleop_general/src/pr2_teleop_general_commander.cpp:41:52: fatal error: kinematics_msgs/GetKinematicSolverInfo.h: No such file or directory
compilation terminated.
make[2]: **\* [pr2_apps/pr2_teleop_general/CMakeFiles/pr2_teleop_general_commander.dir/src/pr2_teleop_general_commander.cpp.o] Error 1
make[1]: **\* [pr2_apps/pr2_teleop_general/CMakeFiles/pr2_teleop_general_commander.dir/all] Error 2
make: **\* [all] Error 2
Invoking "make" failed

**Comment by trainman419** [comment]
It looks like you're missing the [kinematics_msgs](http://wiki.ros.org/kinematics_msgs) package. Given that it's part of the very deprecated arm_navigation stack, it should probably be extracted into its own repository and catkinized.

I'm guessing that @k-okada has already done this

It also looks like the package.xml and CMakeListst are missing the dependency on kinematics_msgs. (this should be failing during dependency resolution rather than during compilation)

**Comment by UltronDestroyer** [comment]
I'm unable to find the source for arm_navigation or kinematics_msgs package. @k-okada , where were you able to find the code for this?

**Comment by k-okada** [comment]
Sorry for late response , yes I catkinized them locally. I should tell you
this first.

I found them at
https://github.com/uos/arm_navigation

So discussion here might be
- catkinized arm_navigation ; does anyone want to do this?
- create kinematics_msgs package ; it works but may not valid at this moment
- do not catkinize packages depends on arm_navigation at this time
- use kinematics server in moveit??

2014年5月31日土曜日、Devon Ashnotifications@github.comさんは書きました:

**Comment by UltronDestroyer** [comment]
It would be nice to use the moveit kin server. Eventually, we will move the pr2 software away from specific things like arm_nav and use more general suites.

Catkinizing arm_nav might be a bit of   work

**Comment by trainman419** [comment]
arm_nav is totally unsupported; we shouldn't bother catkinizing it.

I like the "create kinematics_msgs package" option, because it preserves the existing public API to the pr2 kinematics without dragging in the rest of arm_nav.

Separately, we can rewrite the pr2_kinematics package to use the moveit kinematics server. Overall, this will preserve the existing kinematics API that packages and researchers are using, and still lets us move forward without depending on arm_nav.

**Comment by k-okada** [comment]
ok, I created 
https://github.com/k-okada/arm_navigation_msgs
and 
https://github.com/k-okada/kinematics_msgs
please feel free to download and copy, or please inform me account name to transfer ownership.

**Comment by UltronDestroyer** [comment]
With the above two packages I have successfully compiled the pr2_navigation and I will accept the pull request. 

I'm also copying over arm_navigation_msgs and kinematics_msgs into the PR2 repository and uploading them.

**Comment by UltronDestroyer** [comment]
For interested parties, the packages can be found at http://github.com/pr2/arm_navigation_msgs and http://github.com/pr2/kinematics_msgs

**Comment by k-okada** [comment]
thank you!!!

**Pull request merged**
